name: admin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.1.4
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  firebase_core_web: ^2.10.0
  cloud_firestore: ^5.0.0
  cloud_firestore_web: ^4.0.0
  firebase_messaging: ^15.0.1  # تم إضافتها بالفعل
  firebase_messaging_web: ^3.8.9
  datetime_picker_formfield: ^2.0.0
  url_launcher: ^6.0.9
  intl: ^0.19.0
  path_provider: ^2.0.11
  pdf: ^3.3.0
  printing: ^5.5.0
  http: ^0.13.3
  google_fonts: ^3.0.1
  dropdown_search: ^5.0.2
  rxdart: ^0.27.3
  provider: ^6.0.0
  shared_preferences: ^2.0.0
  share: ^2.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/fonts/Amiri-Regular.ttf
    - assets/notification.mp3

